{
  imports = [
    ./autopairs.nix
    ./bufferline.nix
    ./cmp.nix
    ./comment.nix
    ./conform.nix
    ./dashboard.nix
    ./dressing.nix
    ./fidget.nix
    ./flash.nix
    ./gitsigns.nix
    ./lsp.nix
    ./lspkind.nix
    ./lualine.nix
    ./luasnip.nix
    ./mini.nix
    ./neo-tree.nix
    ./notify.nix
    ./noice.nix
    ./nightfox.nix
    ./telescope.nix
    ./treesitter.nix
    ./trouble.nix
    ./ufo.nix
    ./which-key.nix
  ];
}
